// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Snippet struct {
	ID      int32
	Title   string
	Content string
	Created time.Time
	Expires time.Time
}
