// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamp
}

type Snippet struct {
	ID      int32
	Title   string
	Content string
	Created time.Time
	Expires time.Time
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	Created        time.Time
}
