// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippets.sql

package database

import (
	"context"
)

const createSnippet = `-- name: CreateSnippet :one
INSERT INTO snippets(title, content, created, expires)
VALUES(
        $1,
        $2,
        NOW(),
        NOW() + ($3 * INTERVAL '1 days')
    )
RETURNING id
`

type CreateSnippetParams struct {
	Title   string
	Content string
	Column3 interface{}
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSnippet, arg.Title, arg.Content, arg.Column3)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLatestSnippets = `-- name: GetLatestSnippets :many
SELECT id, title, content, created, expires
FROM snippets
WHERE expires > NOW()
ORDER BY id DESC
LIMIT 10
`

func (q *Queries) GetLatestSnippets(ctx context.Context) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, getLatestSnippets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Created,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippet = `-- name: GetSnippet :one
SELECT id, title, content, created, expires
FROM snippets
WHERE expires > NOW()
    AND id = $1
`

func (q *Queries) GetSnippet(ctx context.Context, id int32) (Snippet, error) {
	row := q.db.QueryRow(ctx, getSnippet, id)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Created,
		&i.Expires,
	)
	return i, err
}
