// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, email, hashed_password, created)
VALUES($1, $2, $3, NOW())
`

type CreateUserParams struct {
	Name           string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Name, arg.Email, arg.HashedPassword)
	return err
}

const getUserViaEmail = `-- name: GetUserViaEmail :one
SELECT id,
    hashed_password
FROM users
WHERE email = $1
`

type GetUserViaEmailRow struct {
	ID             int32
	HashedPassword string
}

func (q *Queries) GetUserViaEmail(ctx context.Context, email string) (GetUserViaEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserViaEmail, email)
	var i GetUserViaEmailRow
	err := row.Scan(&i.ID, &i.HashedPassword)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
        SELECT true
        FROM users
        WHERE id = $1
    )
`

func (q *Queries) UserExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
